FROM apache/superset:latest

USER root

# Создаём venv ТОЧНО там, где Superset его ожидает
RUN python -m venv /app/.venv

# Обновляем pip внутри venv
RUN /app/.venv/bin/pip install --upgrade pip

# Ставим драйвер Postgres ВНУТРЬ venv
RUN /app/.venv/bin/pip install psycopg2-binary

# Проверка на этапе сборки (ВАЖНО)
RUN /app/.venv/bin/python -c "import psycopg2; print(psycopg2.__version__)"

USER superset
