# Allow local connections
local   all             all                                     trust
# Allow password connections from Docker network
host    all             all             0.0.0.0/0               md5
# Allow replication user
host    replication     replicator      0.0.0.0/0               md5
